Brade walder login portal dashboard
Redback-Operations/redback-fit-web pull request #3
Opened 2024-05-09 05:33 UTC by bradewalder

This is still a work in progress.

Functionality is yet to be added, I have created a basic login portal and dashboard (WIP) based around Ojasvi and I's original Figma designs.

2024-05-12 10:05 UTC, MorgaineBarter approved these changes, later dismissed
thank you for sharing this on Friday in the meeting. looks good

2024-05-15 09:34 UTC, MorgaineBarter approved these changes, later dismissed

2024-05-16 08:34 UTC, MorgaineBarter approved these changes, later dismissed

2024-05-16 12:42 UTC, doubleedesign commented
I'll pull and run this code locally ASAP to give more detailed feedback if needed and help get this through, but initial feedback is just to shuffle things around so that each component is in its own folder (inside `src/components`) with its own styling. Some relevant docs published earlier this week:
- [Creating components](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/new-components/) (for the expected directory structure and naming conventions)
- [Using Styled Components](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/styled-components/)
- [Submitting code](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/submitting-work) (more about the linting/structure checks that are now running automatically on PRs to help us keep things consistent)

I'm happy to lend a hand with this if I get time in the next week (but can't promise what time I'll have unfortunately, so don't wait on me).

2024-05-17 06:03 UTC, doubleedesign commented
Have set this up locally; loving the animation to switch between login and signup! There could be a few things here to tweak next trimester and maybe some to bring into Redback UI (also next trimester), but overall once we get it passing the checks I'm happy with this as an MVP to be merged.

2024-05-17 09:41 UTC, ben-AI-cybersec commented
@doubleedesign could you please give us the file naming conventions? The linting errors aren't super clear.

2024-05-17 09:53 UTC, doubleedesign commented
I've just pushed up a change that corrects the directory structure and naming conventions. I can see that in the future we may want to allow component folders within component folders, but I haven't had a change to tinker with that as yet. So for now at least, the basic formula is:

- routes/
  - RouteName/
    - RouteName.tsx
    - RouteName.style.ts
    - RouteName.test.tsx
- components/
  - ComponentName/
    - ComponentName.tsx
    - ComponentName.style.ts
    - ComponentName.test.tsx

Noting that the file names match the folder names, and all are in `PascalCase` (this is the general React convention). 

I suspect there will also be a `hooks` folder in future, when we come across the need for custom hooks (which will follow the React convention of `camelCase` starting with `use`).

2024-05-17 14:26 UTC, bradewalder reviewed
Thank you! Looks great!

2024-05-18 01:16 UTC, doubleedesign commented
No worries @bradewalder! Just the CSS refactoring left now I think, which as discussed on Teams I'm happy to help with ASAP. There's quite a bit here that could potentially be adapted and built upon to be used in other parts of the project and in the other teams' projects too, great work!

2024-05-20 11:02 UTC, doubleedesign commented
As discussed on Teams, I have raised a PR to allow CSS modules in addition to Styled Components for now, as it will help us to finalise this PR and we can easily convert them later when Redback UI is integrated and we are thus more ready for the dynamic stuff that Styled Components makes available.

2024-05-20 14:21 UTC, bradewalder commented
Thank you @doubleedesign! I will keep that in mind for the future. Appreciate your insights, they are very valuable.

2024-09-17 09:51 UTC, doubleedesign requested changes

2024-09-17 09:51 UTC, doubleedesign commented on CODEOWNERS
> +* @bradewalder @Redback-Operations/wearables-for-athletes @Redback-Operations/tutors
@bradewalder Please remove yourself from the codeowners - I know you're a senior student so you probably shouldn't be an approver once you've finished capstone ;)

2024-10-30 10:35 UTC, ben-AI-cybersec approved these changes
Moving T2 work from entire team into main repo so we can work through checking it.

2024-10-30 10:40 UTC, merged